const $=s=>document.querySelector(s);let token=sessionStorage.getItem('access_token'),me,currentApp;
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});if(response.status===401){signOut();throw new Error('Sessão expirada')}if(!response.ok){let data={};try{data=await response.json()}catch{}throw new Error(data.detail||'Não foi possível concluir a operação')}return response.status===204?null:response.json()}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,3000)}
function signOut(){token=null;sessionStorage.removeItem('access_token');$('#dashboard').hidden=true;$('#login').hidden=false}
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();$('#login-error').textContent='';const data=Object.fromEntries(new FormData(event.target));try{const auth=await api('/auth/login',{method:'POST',body:JSON.stringify(data)});token=auth.access_token;sessionStorage.setItem('access_token',token);await start()}catch(error){$('#login-error').textContent=error.message}});
$('#logout').onclick=signOut;
async function start(){try{me=await api('/auth/me');$('#login').hidden=true;$('#dashboard').hidden=false;$('#organization').innerHTML=me.organizations.map(o=>`<option value="${o.id}">${escapeHtml(o.name)} · ${o.role}</option>`).join('');await loadApps()}catch{signOut()}}
$('#organization').onchange=loadApps;
async function loadApps(){currentApp=null;$('#details').hidden=true;$('#empty').hidden=false;const apps=await api(`/organizations/${$('#organization').value}/applications`);$('#applications').innerHTML=apps.map(a=>`<button data-id="${a.id}">${escapeHtml(a.name)}</button>`).join('');$('#applications').querySelectorAll('button').forEach((button,index)=>{button.onclick=()=>selectApp(apps.find(a=>a.id===button.dataset.id),button);if(index===0)button.click()})}
async function selectApp(app,button){currentApp=app;$('#applications').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===button));$('#empty').hidden=true;$('#details').hidden=false;$('#app-name').textContent=app.name;await Promise.all([loadKeys(),loadEndpoints(),loadEvents()])}
async function loadKeys(){const keys=await api(`/applications/${currentApp.id}/api-keys`);$('#keys').innerHTML=keys.length?keys.map(k=>`<div class="card"><strong>${escapeHtml(k.name)}</strong><p><code>${escapeHtml(k.prefix)}…</code></p><p>${k.revoked_at?'Revogada':'Ativa'}</p>${k.revoked_at?'':`<button class="secondary" data-key="${k.id}">Revogar</button>`}</div>`).join(''):'<p class="muted">Nenhuma chave criada.</p>';$('#keys').querySelectorAll('[data-key]').forEach(b=>b.onclick=async()=>{if(confirm('Revogar esta chave?')){await api(`/applications/${currentApp.id}/api-keys/${b.dataset.key}`,{method:'DELETE'});await loadKeys()}})}
async function loadEndpoints(){const rows=await api(`/applications/${currentApp.id}/endpoints`);$('#endpoints').innerHTML=rows.length?rows.map(e=>`<div class="card"><strong>${escapeHtml(e.name)}</strong><p>${escapeHtml(e.url)}</p></div>`).join(''):'<p class="muted">Nenhum endpoint configurado.</p>'}
async function loadEvents(){const rows=await api(`/applications/${currentApp.id}/events`);$('#events').innerHTML=rows.length?rows.map(e=>`<div class="event"><strong>${escapeHtml(e.idempotency_key)}</strong><p>${new Date(e.received_at).toLocaleString()}</p>${e.deliveries.map(d=>`<span class="status ${d.status}">${d.status} · ${d.attempt_count} tentativa(s)</span>`).join(' ')}</div>`).join(''):'<p class="muted">Nenhum evento recebido.</p>'}
$('#new-app').onclick=async()=>{const name=prompt('Nome da aplicação');if(name){await api(`/organizations/${$('#organization').value}/applications`,{method:'POST',body:JSON.stringify({name})});await loadApps()}};
$('#new-key').onclick=async()=>{const name=prompt('Nome da chave');if(name){const key=await api(`/applications/${currentApp.id}/api-keys`,{method:'POST',body:JSON.stringify({name})});$('#secret').hidden=false;$('#secret').innerHTML=`<strong>Copie agora — esta chave só será exibida uma vez.</strong><br><code>${escapeHtml(key.key)}</code>`;await loadKeys()}};
$('#new-endpoint').onclick=async()=>{const name=prompt('Nome do endpoint');if(!name)return;const url=prompt('URL pública (HTTP ou HTTPS)');if(url){try{await api(`/applications/${currentApp.id}/endpoints`,{method:'POST',body:JSON.stringify({name,url})});await loadEndpoints()}catch(error){toast(error.message)}}};
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
if(token)start();
